### ISSUE TITLE
Access seed from old URL

### ISSUE THREAD

**Issue by bigvtokyo** [cashonize/wallet#49]
Since wallet.mycashtokens.org is no longer available, I'm unable to access my BCH and minted NFTs. I hadn't yet backed up the seed phrase prior to the URL change. Is there any way for me to retrieve the seed phrase from my browser's stored IndexedDB for the old URL?

**Comment by mr-zwets** [comment]
Sorry to inform you that this was never an official url used by cashonize, just a copy cat made by someone else.
The old url was cashtokens-wallet.app and is still available.
You can access the seedphrase in indexed Db by pressing F12 -> Storage, Indexed Db -> bitcoin cash (default) -> wallet and there you should see the seedphrase, if the copycat did not delete this or steal your funds somehow....
Hope this helps.

**Comment by bigvtokyo** [comment]
Thanks for the follow up. Harsh lesson!
I'm trying to work out how I ended up using a scammer's url instead of the correct one.  I'd been using it on Chipnet first then mainnet and had successfully tested sending/receiving so presumed (incorrectly) that it was legit.
