### ISSUE TITLE
"Sign" hidden behind an invisible scroll

### ISSUE THREAD

**Issue by dagurval** [cashonize/wallet#65]
The "Sign" button is hidden inside a modal dialog with invisible scroll. 

Suggestion: 
1) Move the "Sign" button to the top. 
2) Always show the "scroll bar"

<img width="548" alt="Screenshot 2024-09-09 at 15 02 55" src="https://github.com/user-attachments/assets/b4fddbdd-09cb-4735-8c66-b7f605e233e3">

(btw; love the auto-sign feature)

**Comment by mr-zwets** [comment]
thanks for the PR Dagur, but this codebase is in the process of being archived right now. 😅 
Hence the renaming to 'legacy-wallet'...

If you hard refresh cashonize.com you should see the new fully rebuilt application.

Closing this issue.
